version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.13.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_HOST: "test_queue_host"
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
  pubcon:
    image: pubcon
    container_name: pubcon
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: "user"
      RABBITMQ_PASS: "password"
    volumes:
      - ./Source/Python:/app/bin/